services:
  postgres:
    image: postgres
    container_name: pocketwatch-drizzle-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - drizzle-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pocketwatch-drizzle-postgres-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - drizzle-network

networks:
  drizzle-network:
    driver: bridge
